name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # Required for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        # This will automatically run lint check and tests via the prebuild script
        # Build will fail if lint issues >= 40 or tests fail
        
      - name: Create release archive
        run: |
          cd dist
          tar -czf ../passive-income-calculator-${{ github.ref_name }}.tar.gz .
          cd ..
          zip -r passive-income-calculator-${{ github.ref_name }}.zip dist/
          
      - name: Extract release notes
        id: extract-notes
        run: |
          # Extract version from tag (remove 'v' prefix if present)
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # Try to extract release notes from CHANGELOG.md if it exists
          if [ -f "CHANGELOG.md" ]; then
            # Extract notes for this version (basic implementation)
            echo "release_notes=Release $VERSION - Built from commit ${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "release_notes=Release $VERSION - Built from commit ${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ steps.extract-notes.outputs.version }}
          body: |
            ${{ steps.extract-notes.outputs.release_notes }}
            
            ## 📋 Build Information
            - **Commit:** ${{ github.sha }}
            - **Build Date:** ${{ github.run_id }}
            - **Node.js Version:** 20
            
            ## ✅ Quality Checks Passed
            - Lint issues: < 40 (requirement met)
            - All tests: ✅ Passed
            
            ## 📦 Assets
            Download the built application from the assets below.
          draft: false
          prerelease: false
          
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./passive-income-calculator-${{ github.ref_name }}.tar.gz
          asset_name: passive-income-calculator-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
          
      - name: Upload Release Assets (ZIP)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./passive-income-calculator-${{ github.ref_name }}.zip
          asset_name: passive-income-calculator-${{ github.ref_name }}.zip
          asset_content_type: application/zip